services:
- docker
script:
- cd $IMG
- docker build -t $IMG .
# container name can't contain / so we replace it with -
- docker run -d --name ${IMG//\//-} $IMG
- docker ps | grep -q ${IMG//\//-}
- cd ${TRAVIS_BUILD_DIR}
env:
  matrix:
  - IMG=base
  global:
  # BINTRAY_SNOWPLOW_DOCKER_USER
  # BINTRAY_SNOWPLOW_DOCKER_API_KEY
deploy:
- provider: script
  script: ./.travis/deploy.sh base $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
    condition: '"$(.travis/is_release_tag.sh base $TRAVIS_TAG)" == "" && $? == 0 && $IMG = base'
